#ifndef PRETTY_PRINT_H
#define PRETTY_PRINT_H
#include <Windows.h>
#include <ostream>

class Zombie;
struct _EXCEPTION_RECORD;
typedef _EXCEPTION_RECORD EXCEPTION_RECORD;
struct _CONTEXT;
typedef _CONTEXT CONTEXT;

enum class Color : WORD {
    FG_BLACK             = 0,
    FG_DARKBLUE          = FOREGROUND_BLUE,
    FG_DARKGREEN         = FOREGROUND_GREEN,
    FG_DARKCYAN          = FOREGROUND_GREEN | FOREGROUND_BLUE,
    FG_DARKRED           = FOREGROUND_RED,
    FG_DARKMAGENTA       = FOREGROUND_RED | FOREGROUND_BLUE,
    FG_DARKYELLOW        = FOREGROUND_RED | FOREGROUND_GREEN,
    FG_DARKGRAY          = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
    FG_GRAY              = FOREGROUND_INTENSITY,
    FG_BLUE              = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
    FG_GREEN             = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
    FG_CYAN              = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,
    FG_RED               = FOREGROUND_INTENSITY | FOREGROUND_RED,
    FG_MAGENTA           = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
    FG_YELLOW            = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
    FG_WHITE             = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,

    BG_BLACK             = 0,
    BG_DARKBLUE          = BACKGROUND_BLUE,
    BG_DARKGREEN         = BACKGROUND_GREEN,
    BG_DARKCYAN          = BACKGROUND_GREEN | BACKGROUND_BLUE,
    BG_DARKRED           = BACKGROUND_RED,
    BG_DARKMAGENTA       = BACKGROUND_RED | BACKGROUND_BLUE,
    BG_DARKYELLOW        = BACKGROUND_RED | BACKGROUND_GREEN,
    BG_DARKGRAY          = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
    BG_GRAY              = BACKGROUND_INTENSITY,
    BG_BLUE              = BACKGROUND_INTENSITY | BACKGROUND_BLUE,
    BG_GREEN             = BACKGROUND_INTENSITY | BACKGROUND_GREEN,
    BG_CYAN              = BACKGROUND_INTENSITY | BACKGROUND_GREEN | BACKGROUND_BLUE,
    BG_RED               = BACKGROUND_INTENSITY | BACKGROUND_RED,
    BG_MAGENTA           = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_BLUE,
    BG_YELLOW            = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN,
    BG_WHITE             = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN | FOREGROUND_BLUE,

    FG_INTENSITY = FOREGROUND_INTENSITY,
};

std::ostream& reset(std::ostream& os);
std::ostream& operator <<(std::ostream& os, Color color);

void printZombieInfo(const Zombie& zombie);
void printExceptionRecord(const EXCEPTION_RECORD& e);
// Only show registers that have had changed
void printRegisters(const CONTEXT& c, const CONTEXT* last_c = nullptr);
#endif